@startuml Datenressourcen

/'
Beispiel
  Datum:        27.09.2019
  Id:           GRDrs 975/2019
  Titel:        Weltklima in Not -Stuttgart handeltAktionsprogramm Klimaschutz 
                -Verwendung des Klimaschutzfonds
  Ausschuss:    Ausschuss für Klima und Umwelt

Zusammengesetzte Werte
    Bezeichnung:    Drucksache 975/2019
    Suchergebnis:   Weltklima in Not - Stuttgart handelt Aktionsprogramm Klimaschutz - Verwendung des Klimaschutzfonds
                    Ausschuss für Klima und Umwelt 
'/
class Beratungsunterlage {
    +datum
    +id
    +titel
    +ausschuss
}
Beratungsunterlage --> "1" Dokument : beschlussvorlage
Beratungsunterlage --> "*" Dokument : anhaenge

/'
Beispiel
  Datum:        24.07.2019
  Identifier:   414
  Betreff:      Aufstellung Jahresabschluss 2018
  Ausschuss:    Verwaltungsausschussdes Gemeinderats der Landeshauptstadt Stuttgart

Zusammengesetzte Werte
    Bezeichnung:    Top 1a - NsNr 414
    Titel:          Aufstellung Jahresabschluss 2018
                    Verwaltungsausschuss 
'/
class Protokoll {
    +datum
    +id
    +betreff
    +ausschuss
}
Protokoll --> "1" Dokument : protokoll
Protokoll --> "1" Beratungsunterlage : verhandlung

/'
Beispiel 
  Datum:        24.10.2019
  Id:           1191/2019
  Betreff:      Aktionsprogramm Klimaschutz
                Wenn´s den Baum dürstet – gießen 
  Fraktion:     Bündnis 90/DIE GRÜNEN-Gemeinderatsfraktion
  Autoren:      Gabriele Nuber-Schöllhammer Andreas Winter

Zusammengesetzte Werte...
  Bezeichnung:  AntragsNr. 1191/2019
  Titel:        Aktionsprogramm Klimaschutz Wenn´s den Baum dürstet – gießen
                Bündnis 90/DIE GRÜNEN-Gemeinderatsfraktion 
'/
class Antrag {
    +datum
    +id
    +betreff
    +fraktion
    +autoren
}
Antrag --> "*" Dokument : anhaenge

'Stellungnahme ist noch nicht analysiert
class Stellungnahme {
}

/'
Beispiel
  Datum:        18.10.2019
  Uhrzeit:      08:30
  Ausschuss:    Ausschuss für Klima und Umwelt
  Inhalt:       ... 
                1 Weltklima in Not - Stuttgart handelt
                Aktionsprogramm Klimaschutz - Verwendung des Klimaschutzfonds
                - Beratung -
                Beratungsunterlagen

                2 Schnell, deutliche Schritte beim Klimawandel: Was tut Stuttgart bisher?
                Antrag 274/2019 vom 17.09.2019 der SPD-Gemeinderatsfraktion
                - mündlicher Bericht -

Tagesordnung besteht aus Text mit Links
'/
class Tagesordnung {
    +datum
    +uhrzeit
    +ausschuss
    +inhalt
}
Tagesordnung --> "*" Tagesordnungspunkt : ordnungspunkt

class Tagesordnungspunkt {
    +titel
}
Tagesordnungspunkt "0...*" --> "0..1" Beratungsunterlage : beratungsunterlage

/'
Beispiel
    url: 
    titel:
    typ: application/pdf, text/plain
'/
class Dokument {
    +url
    +titel
    +typ      
}

/'
Beispiel
  https://www.domino1.stuttgart.de/web/ksd/KSDRedSystem.nsf/ae7aefac3711e63fc1257c67004d7347/b665a8da1aa9f789c125849d00212753?OpenDocument
'/
class Haushaltsantrag {
    +datum
    +fraktion
    +id
    +betreff
    +inhalt
}

/'
Beispiel
  https://www.domino1.stuttgart.de/web/ksd/KSDRedSystem.nsf/ae7aefac3711e63fc1257c67004d7347/14af3f9c529bee2cc125821600423182?OpenDocument
'/
class Anfrage {
    +datum
    +fraktion
    +id
    +betreff
    +inhalt
}
Anfrage --> "0...1" Dokument: zwischennachricht
Anfrage --> "0...1" Dokument: beantwortung

/'
Beispiel: 
  https://www.domino1.stuttgart.de/web/ksd/KSDRedSystem.nsf/ae7aefac3711e63fc1257c67004d7347/c8806a97487617bac125822d002c193d?OpenDocument
'/
class Antrag {
    +datum
    +fraktion
    +id
    +betreff
    +inhalt
}
Antrag --> "0...1" Dokument: stellungnahme

/'
Beispiel
  https://www.domino1.stuttgart.de/web/ksd/KSDRedSystem.nsf/ae7aefac3711e63fc1257c67004d7347/e8913e5cb4af10d1c125824e002c6b1f?OpenDocument
'/
class AntragAnfrage {
    +datum
    +fraktion
    +id
    +betreff
    +inhalt
}
AntragAnfrage --> "0...1" Dokument: beantwortungUndStellungnahme

@enduml